### ISSUE TITLE
VCTK datasets

### ISSUE THREAD

**Issue by XXXHUA** [keonlee9420/StyleSpeech#1]
Hi, I note your paper evaluates the models' performance on VCTK datasets, but I not see the process file about VCTK. Hence, could you share the files, thank you very much.

**Comment by keonlee9420** [comment]
Hi @XXXHUA , actually I'm not the author of the paper 😅. Anyway, you can find what you want in [here](https://github.com/keonlee9420/STYLER). The model uses almost the same preprocessing process on VCTK dataset.

**Comment by XXXHUA** [comment]
Hi, thanks you rely for the question about VCTK datasets, but i faced a new problem on LibriTTS. I load the pretrained model 100000.pth.tar and 600000.pth.tar in this repo, but the synthesize performance is very poor. Have you ever gotten better results？

**Comment by keonlee9420** [comment]
Sorry for the late response. I think it is because the meta-learning part is not perfect yet. I've got to optimize it more and will share the result if I succeeded. Stay tuned!

**Comment by keonlee9420** [comment]
I fixed the optimizer and now can confirm that meta learner is working. I'll share the pre-trained model soon.

**Comment by keonlee9420** [comment]
@XXXHUA and also try to downsample the training data from 22050 to 16k. it will boost up training and also the generated speech quality (compared to the same step of the current pre-trained models)

**Comment by XXXHUA** [comment]
Thanks for your a series of detailed replies, i have tried to use 16KHz data in this model, but i guess the poor performance i faced is result from the 24KHz vocoder. The latest model is trained on 16KHz data ?

**Comment by keonlee9420** [comment]
Ah, I didn't know that you used 24kHz vocoder and yes the mismatch between synthesizer and vocoder is definitely the bottleneck for the poor quality. You may need to match them first. The latest one is also trained on 22050Hz.
