### ISSUE TITLE
What is the perfermance compared with Adaspeech

### ISSUE THREAD

**Issue by Liujingxiu23** [keonlee9420/StyleSpeech#2]
Thank you for your great work and share.
Your work looks differ form adaspeech and NAUTILUS. You use GANs which i did not see in other papers regarding adaptative TTS. 
Have you compare this method with adaspeech1/2?  how about the mos and similarity?

**Comment by keonlee9420** [comment]
Hi @Liujingxiu23 , thank you for the attention. Unfortunately, I didn't have compared this model with adaspeech1/2. If you have any chance to do it, then please share the results here. It would also be helpful for others.

**Comment by Liujingxiu23** [comment]
@keonlee9420  thank you for your reply! 
Adaspeech2 follows the structure of NAUTILUS which is friendly to untranscribed speech data.
The results are of fluent and of relatively high quality, but the similarity is not very high.

**Comment by keonlee9420** [comment]
I see. Thanks for the sharing. What about [Adaspeech3](https://arxiv.org/abs/2107.02530)? Do you have any insight on comparison? I've planed to implement it soon and want to see how it differs from its ancestors and other TTS models.

**Comment by Liujingxiu23** [comment]
@keonlee9420 I have not do experiment of Adaspeech3.

**Comment by keonlee9420** [comment]
Got it. It could be interesting to compare it too after then.

**Comment by keonlee9420** [comment]
Close due to inactivity.

**Comment by Pydataman** [comment]
> @keonlee9420 thank you for your reply! Adaspeech2 follows the structure of NAUTILUS which is friendly to untranscribed speech data. The results are of fluent and of relatively high quality, but the similarity is not very high.

test in Zn？ how many speakers of data？ I use own data,2 speakers ,but bad
do you have weixin?

**Comment by Pydataman** [comment]
@Liujingxiu23 hi 
how can i contact you

**Comment by Liujingxiu23** [comment]
@Pydataman  2 speakers are too few， I guess 500~2000+ may be suitable.

**Comment by Pydataman** [comment]
> @Pydataman 2 speakers are too few， I guess 500~2000+ may be suitable.

@Liujingxiu23  how many speakers did you test?
