### ISSUE TITLE
There was a problem when starting training

### ISSUE THREAD

**Issue by huanchen-1** [keonlee9420/StyleSpeech#5]
When I tried to train, this problem appeared： No such file or directory: './preprocessed_data/LibriTTS\\mel\\7067-mel-7067_76048_000075_000003.npy'

**Comment by keonlee9420** [comment]
Hi @huanchen-1, did you preprocess LibriTTS following README.md? If not, please complete the preprocessing first and then try again.

**Comment by keonlee9420** [comment]
Close due to inactivity.
